# Exercise 5.1

In [327]:
import pandas as pd

In [328]:
obj = pd.Series([4,7,-5,3])

In [329]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [330]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [331]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [332]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [333]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [334]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [335]:
obj2['a']

-5

In [336]:
obj2['d']=6

In [337]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [338]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [339]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [340]:
import numpy as np

In [341]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [342]:
'b' in obj2

True

In [343]:
'e' in obj2

False

In [344]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [345]:
obj3 = pd.Series(sdata)

In [346]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [347]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [348]:
obj4 = pd.Series(sdata, index=states)

In [349]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [350]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [351]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [352]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [353]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [354]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [355]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [356]:
obj4.name = 'population'

In [357]:
obj4.index.name = 'state'

In [358]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [359]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [360]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [361]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [362]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.6,3.2]}

In [363]:
frame = pd.DataFrame(data)

In [364]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.6
5  Nevada  2003  3.2

In [365]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.6

In [366]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.6
5  2003  Nevada  3.2

In [367]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],
                     index = ['one','two','three','four','five','six'])

In [368]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.6  NaN
six    2003  Nevada  3.2  NaN

In [369]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [370]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [371]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [372]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [373]:
frame2['debt']=16.5

In [374]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.6  16.5
six    2003  Nevada  3.2  16.5

In [375]:
frame2['debt']=np.arange(6.)

In [376]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.6   4.0
six    2003  Nevada  3.2   5.0

In [377]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [378]:
frame2['debt']=val

In [379]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.6  -1.7
six    2003  Nevada  3.2   NaN

In [380]:
frame2['eastern'] = (frame2.state == 'Ohio')

In [381]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.6  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [382]:
del frame2['eastern']

In [383]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [384]:
pop = {'Nevada':{2001: 2.4,2002: 2.9},
       'Ohio':{2000: 1.5,2001: 1.7,2002: 3.6}}

In [385]:
frame3 = pd.DataFrame(pop)

In [386]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [387]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [388]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [389]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [390]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [391]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [392]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [393]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [394]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.6  -1.7
six    2003  Nevada  3.2   NaN

In [395]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.6, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [396]:
obj = pd.Series(range(3), index=['a','b','c'])

In [397]:
index = obj.index

In [398]:
index

Index(['a', 'b', 'c'], dtype='object')

In [399]:
index[1:]

Index(['b', 'c'], dtype='object')

In [400]:
index[1]='d'
#Type Error

TypeError: Index does not support mutable operations

In [ ]:
labels = pd.Index(np.arange(3))

In [ ]:
labels

In [ ]:
obj2 = pd.Series([1.5, -2.5,0],index=labels)

In [ ]:
obj2

In [ ]:
obj2.index is labels

In [ ]:
frame3

In [ ]:
frame3.columns

In [ ]:
'Ohio' in frame3.columns

In [ ]:
2003 in frame3.index

In [ ]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [ ]:
dup_labels

In [ ]:
du_label = pd.Index(['Adam','Cole','foo','foo'])

In [ ]:
dup_labels.append(du_label)

In [ ]:
dup_labels

In [ ]:
dup_labels.difference(du_label)

In [ ]:
dup_labels.intersection(du_label)

In [ ]:
dup_labels.union(du_label)

In [ ]:
dup_labels.isin(du_label)

In [ ]:
dup_labels.delete(3)

In [ ]:
dup_labels.drop('foo')

In [ ]:
dup_labels.insert(1,'for')

In [ ]:
numbers = pd.Index([1,2,4,5,7,8,9])

In [ ]:
numbers.is_monotonic

In [ ]:
numbers.is_unique

In [ ]:
numbers.unique()

# Exercise 5.2

In [402]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [403]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [404]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [405]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [406]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [407]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [408]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [409]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
        index=['a', 'c', 'd'],columns=['Ohio', 'Texas', 'California'])

In [410]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [411]:
frame2 = frame.reindex(['a','b','c','d'])

In [412]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [413]:
states = ['Texas', 'Utah', 'California']

In [414]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [415]:
frame2.loc[['a', 'b', 'c', 'd'], states]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['Utah'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [417]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [418]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [419]:
new_obj = obj.drop('c')

In [420]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [421]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [422]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [423]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [424]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [425]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [426]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [427]:
obj.drop('c', inplace=True)

In [428]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [429]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [430]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [431]:
obj['b']

1.0

In [432]:
obj[1]

1.0

In [433]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [434]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [435]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [436]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [437]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [438]:
obj['b':'c'] = 5

In [439]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [440]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [441]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [442]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [443]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [444]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [445]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [446]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [447]:
data[data<5]=0

In [448]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [449]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [450]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [451]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [452]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [453]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [454]:
data.iloc[:,:3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [455]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [456]:
ser = pd.Series(np.arange(3.))

In [457]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [458]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [459]:
ser2[-1]

2.0

In [460]:
ser[:1]

0    0.0
dtype: float64

In [461]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [462]:
ser.iloc[:1]

0    0.0
dtype: float64

In [463]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [464]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [465]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [466]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [467]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [468]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

In [469]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [470]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [471]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [472]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [473]:
df1 = pd.DataFrame({'A': [1, 2]})

In [474]:
df2 = pd.DataFrame({'B': [3, 4]})

In [475]:
df1

A
0  1
1  2

In [476]:
df2

B
0  3
1  4

In [477]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [478]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

In [479]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [480]:
df2.loc[1, 'b'] = np.nan

In [481]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [482]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [483]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [484]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [485]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [486]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [487]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [488]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [489]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [490]:
df1.div(1)

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [491]:
arr = np.arange(12.).reshape((3, 4))

In [492]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [493]:
arr[0]

array([0., 1., 2., 3.])

In [494]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [495]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [496]:
series = frame.iloc[0]

In [497]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [498]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [499]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [500]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [501]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [502]:
series3 = frame['d']

In [503]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [504]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [505]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [506]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [507]:
frame

b         d         e
Utah    0.225964 -1.908936 -0.745255
Ohio    1.509987 -0.401626  0.837911
Texas  -0.571504  1.169014 -0.196188
Oregon -1.843974  1.236295  0.361289

In [508]:
np.abs(frame)

b         d         e
Utah    0.225964  1.908936  0.745255
Ohio    1.509987  0.401626  0.837911
Texas   0.571504  1.169014  0.196188
Oregon  1.843974  1.236295  0.361289

In [509]:
frame

b         d         e
Utah    0.225964 -1.908936 -0.745255
Ohio    1.509987 -0.401626  0.837911
Texas  -0.571504  1.169014 -0.196188
Oregon -1.843974  1.236295  0.361289

In [510]:
f = lambda x: x.max() - x.min()

In [511]:
frame.apply(f)

b    3.353960
d    3.145230
e    1.583166
dtype: float64

In [512]:
frame.apply(f, axis='columns')

Utah      2.134900
Ohio      1.911613
Texas     1.740519
Oregon    3.080269
dtype: float64

In [513]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [514]:
frame.apply(f)

b         d         e
min -1.843974 -1.908936 -0.745255
max  1.509987  1.236295  0.837911

In [515]:
format = lambda x: '%.2f' % x

In [516]:
frame.applymap(format)

b      d      e
Utah     0.23  -1.91  -0.75
Ohio     1.51  -0.40   0.84
Texas   -0.57   1.17  -0.20
Oregon  -1.84   1.24   0.36

In [517]:
frame['e'].map(format)

Utah      -0.75
Ohio       0.84
Texas     -0.20
Oregon     0.36
Name: e, dtype: object

In [518]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [519]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [520]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [521]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [522]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [523]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [524]:
obj = pd.Series([4, 7, -3, 2])

In [525]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [526]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [527]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [528]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [529]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [530]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [531]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [532]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [533]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [534]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [535]:
# Assign tie values the maximum rank in the group

In [536]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [537]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})

In [538]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [539]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [540]:
obj.rank(ascending=False, method='average')

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [541]:
obj.rank(ascending=False, method='min')

0    1.0
1    7.0
2    1.0
3    3.0
4    5.0
5    6.0
6    3.0
dtype: float64

In [542]:
obj.rank(ascending=False, method='first')

0    1.0
1    7.0
2    2.0
3    3.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [543]:
obj.rank(ascending=False, method='dense')

0    1.0
1    5.0
2    1.0
3    2.0
4    3.0
5    4.0
6    2.0
dtype: float64

In [544]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [545]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [546]:
obj.index.is_unique

False

In [547]:
obj['a']

a    0
a    1
dtype: int64

In [548]:
obj['c']

4

In [549]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [550]:
df

0         1         2
a -0.634694  0.527811 -0.345367
a -0.123444 -0.062665  1.657901
b -1.069138  0.688398 -0.534989
b -0.780056  2.039481  0.184269

In [551]:
df.loc['b']

0         1         2
b -1.069138  0.688398 -0.534989
b -0.780056  2.039481  0.184269

# Exercise 5.3

In [552]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])

In [553]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [554]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [555]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [556]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [557]:
df.idxmax()

one    b
two    d
dtype: object

In [558]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [559]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [560]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [561]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [562]:
obj.count()

16

In [563]:
obj.min()

'a'

In [564]:
obj.max()

'c'

In [565]:
obj = pd.Index([4,7,5,6,1,2,9,8,3])

In [566]:
obj.argmin()

4

In [567]:
obj.argmax()

6

In [568]:
obj.min()

1

In [569]:
obj.max()

9

In [570]:
import numpy as np

In [571]:
dfa=pd.DataFrame(np.random.randint(1,20,12).reshape(3,4),index=['A','B','C'],columns=['Q1','Q2','Q3','Q4'])
dfb=pd.DataFrame(np.random.randint(1,20,12).reshape(3,4),index=['D','E','F'],columns=['Q1','Q2','Q3','Q4'])

In [572]:
df = pd.concat([dfa,dfb])

In [573]:
df

Q1  Q2  Q3  Q4
A   9  18   6  10
B   2   5  11  19
C  14  19   3   7
D   1   3  14  12
E   9  14  19  15
F   5   3   3   7

In [574]:
df.count()

Q1    6
Q2    6
Q3    6
Q4    6
dtype: int64

In [575]:
df.describe()

Q1         Q2         Q3         Q4
count   6.000000   6.000000   6.000000   6.000000
mean    6.666667  10.333333   9.333333  11.666667
std     4.926121   7.527727   6.470446   4.718757
min     1.000000   3.000000   3.000000   7.000000
25%     2.750000   3.500000   3.750000   7.750000
50%     7.000000   9.500000   8.500000  11.000000
75%     9.000000  17.000000  13.250000  14.250000
max    14.000000  19.000000  19.000000  19.000000

In [576]:
df.min()

Q1    1
Q2    3
Q3    3
Q4    7
dtype: int32

In [577]:
df.max()

Q1    14
Q2    19
Q3    19
Q4    19
dtype: int32

In [578]:
df.cumprod()

Q1      Q2      Q3       Q4
A      9      18       6       10
B     18      90      66      190
C    252    1710     198     1330
D    252    5130    2772    15960
E   2268   71820   52668   239400
F  11340  215460  158004  1675800

In [579]:
df.cumsum()

Q1  Q2  Q3  Q4
A   9  18   6  10
B  11  23  17  29
C  25  42  20  36
D  26  45  34  48
E  35  59  53  63
F  40  62  56  70

In [580]:
df.cummin()

Q1  Q2  Q3  Q4
A   9  18   6  10
B   2   5   6  10
C   2   5   3   7
D   1   3   3   7
E   1   3   3   7
F   1   3   3   7

In [581]:
df.cummax()

Q1  Q2  Q3  Q4
A   9  18   6  10
B   9  18  11  19
C  14  19  11  19
D  14  19  14  19
E  14  19  19  19
F  14  19  19  19

In [582]:
df.skew()

Q1    0.330153
Q2    0.148002
Q3    0.514343
Q4    0.638299
dtype: float64

In [583]:
df.kurt()
#don't know what it does

Q1   -0.943047
Q2   -2.790353
Q3   -1.236029
Q4   -0.642458
dtype: float64

In [584]:
df.idxmin()

Q1    D
Q2    D
Q3    C
Q4    C
dtype: object

In [585]:
df.idxmax()

Q1    C
Q2    C
Q3    E
Q4    B
dtype: object

In [586]:
df.quantile()

Q1     7.0
Q2     9.5
Q3     8.5
Q4    11.0
Name: 0.5, dtype: float64

In [587]:
df.sum()

Q1    40
Q2    62
Q3    56
Q4    70
dtype: int64

In [588]:
df.mean()

Q1     6.666667
Q2    10.333333
Q3     9.333333
Q4    11.666667
dtype: float64

In [589]:
df.median()

Q1     7.0
Q2     9.5
Q3     8.5
Q4    11.0
dtype: float64

In [590]:
df.mad

<bound method NDFrame._add_numeric_operations.<locals>.mad of    Q1  Q2  Q3  Q4
A   9  18   6  10
B   2   5  11  19
C  14  19   3   7
D   1   3  14  12
E   9  14  19  15
F   5   3   3   7>

In [591]:
df.prod()

Q1      11340
Q2     215460
Q3     158004
Q4    1675800
dtype: int32

In [592]:
df.var()

Q1    24.266667
Q2    56.666667
Q3    41.866667
Q4    22.266667
dtype: float64

In [593]:
df.std()

Q1    4.926121
Q2    7.527727
Q3    6.470446
Q4    4.718757
dtype: float64

In [594]:
df.cumsum()

Q1  Q2  Q3  Q4
A   9  18   6  10
B  11  23  17  29
C  25  42  20  36
D  26  45  34  48
E  35  59  53  63
F  40  62  56  70

In [595]:
df.cumprod()

Q1      Q2      Q3       Q4
A      9      18       6       10
B     18      90      66      190
C    252    1710     198     1330
D    252    5130    2772    15960
E   2268   71820   52668   239400
F  11340  215460  158004  1675800