In [1]:
import numpy as np

In [2]:
points = np.arange(-5, 5, 0.05)

In [3]:
len(points)

200

In [4]:
points

array([-5.00000000e+00, -4.95000000e+00, -4.90000000e+00, -4.85000000e+00,
       -4.80000000e+00, -4.75000000e+00, -4.70000000e+00, -4.65000000e+00,
       -4.60000000e+00, -4.55000000e+00, -4.50000000e+00, -4.45000000e+00,
       -4.40000000e+00, -4.35000000e+00, -4.30000000e+00, -4.25000000e+00,
       -4.20000000e+00, -4.15000000e+00, -4.10000000e+00, -4.05000000e+00,
       -4.00000000e+00, -3.95000000e+00, -3.90000000e+00, -3.85000000e+00,
       -3.80000000e+00, -3.75000000e+00, -3.70000000e+00, -3.65000000e+00,
       -3.60000000e+00, -3.55000000e+00, -3.50000000e+00, -3.45000000e+00,
       -3.40000000e+00, -3.35000000e+00, -3.30000000e+00, -3.25000000e+00,
       -3.20000000e+00, -3.15000000e+00, -3.10000000e+00, -3.05000000e+00,
       -3.00000000e+00, -2.95000000e+00, -2.90000000e+00, -2.85000000e+00,
       -2.80000000e+00, -2.75000000e+00, -2.70000000e+00, -2.65000000e+00,
       -2.60000000e+00, -2.55000000e+00, -2.50000000e+00, -2.45000000e+00,
       -2.40000000e+00, -

In [5]:
xs,ys = np.meshgrid(points,points)

In [6]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.95, -4.95, -4.95, ..., -4.95, -4.95, -4.95],
       [-4.9 , -4.9 , -4.9 , ..., -4.9 , -4.9 , -4.9 ],
       ...,
       [ 4.85,  4.85,  4.85, ...,  4.85,  4.85,  4.85],
       [ 4.9 ,  4.9 ,  4.9 , ...,  4.9 ,  4.9 ,  4.9 ],
       [ 4.95,  4.95,  4.95, ...,  4.95,  4.95,  4.95]])

In [7]:
xs

array([[-5.  , -4.95, -4.9 , ...,  4.85,  4.9 ,  4.95],
       [-5.  , -4.95, -4.9 , ...,  4.85,  4.9 ,  4.95],
       [-5.  , -4.95, -4.9 , ...,  4.85,  4.9 ,  4.95],
       ...,
       [-5.  , -4.95, -4.9 , ...,  4.85,  4.9 ,  4.95],
       [-5.  , -4.95, -4.9 , ...,  4.85,  4.9 ,  4.95],
       [-5.  , -4.95, -4.9 , ...,  4.85,  4.9 ,  4.95]])

In [8]:
z = np.sqrt(xs ** 2 + ys ** 2)

In [9]:
z

array([[7.07106781, 7.0358013 , 7.00071425, ..., 6.96580936, 7.00071425,
        7.0358013 ],
       [7.0358013 , 7.00035713, 6.96509153, ..., 6.93000722, 6.96509153,
        7.00035713],
       [7.00071425, 6.96509153, 6.92964646, ..., 6.89438177, 6.92964646,
        6.96509153],
       ...,
       [6.96580936, 6.93000722, 6.89438177, ..., 6.85893578, 6.89438177,
        6.93000722],
       [7.00071425, 6.96509153, 6.92964646, ..., 6.89438177, 6.92964646,
        6.96509153],
       [7.0358013 , 7.00035713, 6.96509153, ..., 6.93000722, 6.96509153,
        7.00035713]])

In [10]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [11]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

A Random Condition

In [12]:
cond = np.array([True, False, True, True, False])

In [13]:
result = np.where(cond, xarr, yarr)

In [14]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [15]:
arr = np.random.randn(4,4)

In [16]:
arr

array([[ 0.49950965,  2.28130549, -0.14640057, -0.745542  ],
       [ 0.7096905 , -1.90058616, -0.38092965,  0.84163442],
       [ 0.49082562,  0.44732678,  1.87359327, -1.02069883],
       [-0.33841274, -0.64342256,  0.40674673, -0.56946249]])

In [17]:
arr>0

array([[ True,  True, False, False],
       [ True, False, False,  True],
       [ True,  True,  True, False],
       [False, False,  True, False]])

In [18]:
np.where(arr>0,2,-2)

array([[ 2,  2, -2, -2],
       [ 2, -2, -2,  2],
       [ 2,  2,  2, -2],
       [-2, -2,  2, -2]])

In [19]:
ra = np.arange(25)

In [20]:
ra.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
np.where(ra<10, 1, ra)

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
a = [4,-1,5,-7]

In [23]:
ar = np.array(a)

In [24]:
np.min(ar)

-7

In [25]:
np.argmin(ar)

3

In [26]:
arr = np.random.randn(5,4)

In [27]:
arr

array([[-0.55878421,  0.137563  ,  0.02819838, -0.38960453],
       [ 1.32024125, -0.65469016,  0.86605302,  0.29164426],
       [-0.30039353,  2.89890659,  0.86196382, -1.56887885],
       [-0.60323554,  1.0198365 ,  0.55847967,  0.59416899],
       [-0.63347608, -0.58612739,  1.76694691, -2.61778265]])

In [28]:
arr.sum(axis=0)

array([-0.77564812,  2.81548855,  4.08164179, -3.69045278])

In [29]:
arr.sum(axis=1)

array([-0.78262737,  1.82324837,  1.89159804,  1.56924961, -2.07043922])

In [30]:
arr.mean(axis=0)

array([-0.15512962,  0.56309771,  0.81632836, -0.73809056])

In [31]:
arr.mean(axis=1)

array([-0.19565684,  0.45581209,  0.47289951,  0.3923124 , -0.5176098 ])

In [32]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [35]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8],[9, 10, 11]])

In [36]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26]], dtype=int32)

In [38]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
arr.cumprod(axis=0)

array([[  0,   1,   2],
       [  0,   4,  10],
       [  0,  28,  80],
       [  0, 280, 880]], dtype=int32)

In [40]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336],
       [  9,  90, 990]], dtype=int32)

In [41]:
arr = np.random.randn(100)

In [42]:
(arr > 0).sum()

46

In [43]:
bools = np.array([False, False, True, False])

In [44]:
bools.any()

True

In [45]:
bools.all()

False

In [46]:
arr = np.random.randn(6)

In [47]:
arr

array([-2.5712165 ,  0.16067418, -2.54659402, -0.58413549, -0.43442838,
       -0.22856486])

In [48]:
arr.sort()

In [49]:
arr

array([-2.5712165 , -2.54659402, -0.58413549, -0.43442838, -0.22856486,
        0.16067418])

In [50]:
arr = np.random.randn(5, 3)

In [51]:
arr

array([[-0.94887016, -1.34032572,  0.27193199],
       [ 0.58281841,  1.04649428, -1.69669613],
       [-1.00270785, -0.32812284,  0.05197827],
       [ 0.82157915, -1.42655585, -0.22813473],
       [-0.22329011, -0.26798942, -0.19956231]])

In [52]:
ar = arr.copy()

In [53]:
arr.sort()

In [54]:
arr

array([[-1.34032572, -0.94887016,  0.27193199],
       [-1.69669613,  0.58281841,  1.04649428],
       [-1.00270785, -0.32812284,  0.05197827],
       [-1.42655585, -0.22813473,  0.82157915],
       [-0.26798942, -0.22329011, -0.19956231]])

In [55]:
ar.sort(0)

In [56]:
ar

array([[-1.00270785, -1.42655585, -1.69669613],
       [-0.94887016, -1.34032572, -0.22813473],
       [-0.22329011, -0.32812284, -0.19956231],
       [ 0.58281841, -0.26798942,  0.05197827],
       [ 0.82157915,  1.04649428,  0.27193199]])

In [57]:
x = np.array([1,2,3,4,5])

In [58]:
y = np.array([5,6,7,8,9])

In [59]:
np.intersect1d(x,y)

array([5])

In [60]:
np.union1d(x,y)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.in1d(x,y)

array([False, False, False, False,  True])

In [62]:
np.setdiff1d(x,y)

array([1, 2, 3, 4])

In [63]:
np.setxor1d(x,y)

array([1, 2, 3, 4, 6, 7, 8, 9])

Classwork

In [64]:
arr = np.random.randn(6)

In [65]:
arr

array([ 0.6309913 ,  0.43592922,  0.08893134,  0.95881768, -0.86350072,
       -0.25117119])

In [66]:
arr.sort()

In [67]:
arr

array([-0.86350072, -0.25117119,  0.08893134,  0.43592922,  0.6309913 ,
        0.95881768])

In [68]:
large_arr = np.random.randn(1000)

In [69]:
large_arr.sort()

In [70]:
large_arr[int(0.05 * len(large_arr))]

-1.6225804476078194

In [71]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [72]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [73]:
values = np.array([6, 0, 0, 3, 2, 5, 6])

In [74]:
np.in1d(values, [2,3,6])

array([ True, False, False,  True,  True, False,  True])

In [75]:
arr=np.arange(9)

In [76]:
np.save('Save_Array', arr)

In [77]:
np.load('Save_Array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
barr=np.arange(6)

In [79]:
np.savez('array_archive.npz', a=arr, b=barr)

In [80]:
arch = np.load('array_archive.npz')

In [81]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
arch['b']

array([0, 1, 2, 3, 4, 5])

In [83]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)