In [89]:
#NumPy

In [90]:
import numpy as np

In [91]:
my_list=[11,22,33,44,55]

In [92]:
narr=np.array(my_list)

In [93]:
type(my_list)

list

In [94]:
type(narr)

numpy.ndarray

In [95]:
narr.dtype

dtype('int32')

In [96]:
my_list2=[[1,2,3,4],[5,6,7,8]]

In [97]:
n2arr=np.array(my_list2)

In [98]:
type(n2arr)

numpy.ndarray

In [99]:
n2arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [100]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [101]:
var = np.arange(5)

In [102]:
var

array([0, 1, 2, 3, 4])

In [103]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.arange(1,10,3)

array([1, 4, 7])

In [105]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [106]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [108]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [109]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [110]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [111]:
np.random.rand(5)

array([0.98135674, 0.67006779, 0.10672024, 0.30194392, 0.98145884])

In [112]:
np.random.rand(2,5)

array([[0.86597637, 0.96357273, 0.28946383, 0.54629122, 0.41870428],
       [0.09706792, 0.94334942, 0.76538375, 0.78472597, 0.51138646]])

In [113]:
np.random.randn(6,2)

array([[ 0.21562924, -1.03603991],
       [-1.02665147, -0.9458697 ],
       [-1.71859574,  1.14556327],
       [ 1.03255131,  0.75292656],
       [ 1.05571452,  0.12223117],
       [-0.6136153 ,  1.6166796 ]])

In [114]:
np.random.randint(5)

2

In [115]:
np.random.randint(5,10)

9

In [116]:
np.random.randint(5,10,10)

array([8, 7, 7, 6, 9, 6, 6, 8, 6, 7])

In [161]:
rollno=np.arange(1,21)

In [118]:
rollno

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [119]:
rollno.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [120]:
rollno.reshape(1,20)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [121]:
rollno.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [122]:
rollno.shape

(20,)

In [123]:
rollno.reshape(1,-1).shape

(1, 20)

In [124]:
rollno.reshape(2,10).shape

(2, 10)

In [162]:
rollno1=rollno.reshape(4,5)

In [163]:
rollno1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [127]:
type(rollno1)

numpy.ndarray

In [128]:
rollno1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [129]:
rollno1[2,:]

array([11, 12, 13, 14, 15])

In [130]:
rollno1[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

In [131]:
rollno1[1:3,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [132]:
rollno1[-1,-1]

20

In [133]:
rollno2=rollno

In [134]:
rollno2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [135]:
rollno2[5:10]=-1

In [136]:
rollno2

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [137]:
rollno

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

changes made in rollno2 reflected in rollno 
Call by Reference issue

In [138]:
rollno3=rollno.copy()

In [139]:
rollno3[10:12]=-1

In [140]:
rollno3

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1, -1, -1, 13, 14, 15, 16, 17,
       18, 19, 20])

In [141]:
rollno

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [142]:
rollno=np.arange(1,21)

In [143]:
rollno

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [144]:
rollno>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [145]:
rollno[rollno>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [146]:
rollno[rollno>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [147]:
rollno2+2

array([ 3,  4,  5,  6,  7,  1,  1,  1,  1,  1, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22])

In NumPy Array this is allowed but in list this isn't allowed

In [148]:
list11=[2,3]

In [149]:
list11+4

TypeError: can only concatenate list (not "int") to list

Example of In NumPy Array this is allowed but in list this isn't allowed

In [151]:
np.min(rollno)

1

In [152]:
np.max(rollno)

20

In [159]:
np.sum(rollno)

210

In [164]:
rollno1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [165]:
np.sum(rollno1,axis=0)

array([34, 38, 42, 46, 50])

sum of elements column wise

In [166]:
np.sum(rollno1,axis=1)

array([15, 40, 65, 90])

sum of elements row wise

In [156]:
np.max(rollno)+np.min(rollno)

21

In [157]:
np.median(rollno)

10.5

In [158]:
rollno1

array([[ 1,  2,  3,  4,  5],
       [-1, -1, -1, -1, -1],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])