In [1]:
#Numpy
#ndarray

In [3]:
import numpy as np

In [4]:
my_list=[11,22,33,44,55]

In [5]:
narr=np.array(my_list)

In [6]:
type(my_list)

list

In [7]:
type(narr)

numpy.ndarray

In [9]:
narr.dtype

dtype('int64')

In [10]:
my_list2=[[1,2,3],[4,5,6]]

In [11]:
my_list2

[[1, 2, 3], [4, 5, 6]]

In [12]:
n2arr=np.array(my_list2)

In [13]:
type(n2arr)

numpy.ndarray

In [14]:
n2arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
var=np.arange(5)

In [17]:
var


array([0, 1, 2, 3, 4])

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(1,10,3)

array([1, 4, 7])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [24]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(5)

array([0.39646321, 0.91884282, 0.67318372, 0.95487379, 0.80012003])

In [28]:
np.random.rand(2,5)

array([[0.62210847, 0.36358453, 0.33016175, 0.08771009, 0.61753125],
       [0.23635784, 0.59825807, 0.14251189, 0.86616912, 0.59656501]])

In [31]:
np.random.randn(6,2)

array([[ 0.92586865, -0.33596413],
       [ 0.18386184, -0.28805762],
       [-0.60406467,  0.76337087],
       [-0.67814566, -0.34710702],
       [-3.05275283, -0.73427905],
       [-0.73822773, -1.28612411]])

In [39]:
np.random.randint(5)

3

In [44]:
np.random.randint(5,10)

5

In [45]:
np.random.randint(5,10,10)

array([5, 5, 7, 9, 8, 5, 7, 8, 8, 6])

In [47]:
rollno=np.arange(1,21)

In [48]:
rollno

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
rollno.reshape(2,11)

ValueError: cannot reshape array of size 20 into shape (2,11)

In [52]:
rollno.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [54]:
rollno.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [55]:
rollno.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [56]:
rollno.shape

(20,)

In [58]:
rollno.reshape(-1,1).shape

(20, 1)

In [59]:
rollno1=rollno.reshape(4,5)

In [60]:
rollno1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [61]:
type(rollno1)

numpy.ndarray

In [62]:
rollno1[2,:]

array([11, 12, 13, 14, 15])

In [63]:
rollno1[2][:]

array([11, 12, 13, 14, 15])

In [77]:
rollno1[1:3]


array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [78]:
rollno1[1:3,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [79]:
rollno1[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

In [90]:
rollno1[-1:,-1]

array([20])

In [91]:
rollno

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [92]:
rollno2=rollno

In [93]:
rollno2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [94]:
rollno2[5:10]=-1

In [95]:
rollno2

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [96]:
rollno

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [97]:
rollno3=rollno.copy()

In [98]:
rollno3[10:15]=-9   #Broadcasting

In [99]:
rollno3

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1, -9, -9, -9, -9, -9, 16, 17,
       18, 19, 20])

In [100]:
rollno

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

conditional selection

In [101]:
rollno

array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [102]:
rollno=np.arange(1,21)

In [103]:
rollno

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [104]:
rollno>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [105]:
rollno[rollno>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [117]:
rollno+20

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40])

In [118]:
list1=[11,22]

In [119]:
list1+10

TypeError: can only concatenate list (not "int") to list

In [120]:
rollno+rollno

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

universal function

In [121]:
rollno

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [122]:
rollno.max()

20

In [123]:
np.max(rollno)

20

In [124]:
np.min(rollno)

1

In [126]:
np.sum(rollno)

210

In [127]:
np.sum(rollno1)

165

In [128]:
rollno1

array([[ 1,  2,  3,  4,  5],
       [-1, -1, -1, -1, -1],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [129]:
np.sum(rollno1,axis=0)

array([27, 30, 33, 36, 39])

In [130]:
np.sum(rollno1,axis=1)

array([15, -5, 65, 90])

In [131]:
np.max(rollno1,0)

array([16, 17, 18, 19, 20])

In [132]:
np.max(rollno1,1)

array([ 5, -1, 15, 20])

In [136]:
rollno4=rollno.copy('F')

In [137]:
rollno4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [139]:
np.max(rollno)+np.min(rollno)

21

In [ ]:
np.median