In [1]:
import numpy as np

1. Create an array of 5 ones

In [3]:
arr1 = np.ones(5)

In [4]:
arr1

array([1., 1., 1., 1., 1.])

2. Create an array of 5 fives

In [8]:
arr2 = 5*np.ones(5)

In [9]:
arr2

array([5., 5., 5., 5., 5.])

3. Create a 1-D array of 100 linearly spaced values between 1 and 10. Covert into 10 by 10 2-D array.

In [11]:
arr3 = np.linspace(1,10,100)

In [12]:
arr3

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [13]:
arr3.reshape(10,10)

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909

4. Create an array of integers in sequence, from 1 to 10.

In [14]:
arrseq = np.arange(1,11)

In [15]:
arrseq

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

5. Create an array with 10 random integer values between 12 and 15, excluding 15.

In [8]:
arr5 = np.random.randint(12,15,10)

In [9]:
arr5

array([12, 14, 13, 13, 13, 12, 14, 12, 13, 13])

6. Create the following array ‘arrfreq’ with 4 readings of 9 frequencies each.

12.5, 14, 21, 4, 5, 34, 5, 23, 23

21, 12, 22, 4.25, 7, 23, 52, 72, 21

34.5, 45, 34, 7, 8, 25, 6, 25, 20

18, 14.4, 20.1, 41, 15, 4, 15, 43, 23

From the array ‘arrfreq’ select:

a. The complete first reading

b. The last frequency of each reading

c. The 2nd to 5th frequency of each reading

d. Upto the third frequency of the last two reading

In [10]:
arr6 = [[12.5, 14, 21, 4, 5, 34, 5, 23, 23],[21, 12, 22, 4.25, 7, 23, 52, 72, 21],[34.5, 45, 34, 7, 8, 25, 6, 25, 20],[18, 14.4, 20.1, 41, 15, 4, 15, 43, 23]]

In [11]:
arrfreq = np.array(arr6).reshape(4,9)

In [12]:
arrfreq

array([[12.5 , 14.  , 21.  ,  4.  ,  5.  , 34.  ,  5.  , 23.  , 23.  ],
       [21.  , 12.  , 22.  ,  4.25,  7.  , 23.  , 52.  , 72.  , 21.  ],
       [34.5 , 45.  , 34.  ,  7.  ,  8.  , 25.  ,  6.  , 25.  , 20.  ],
       [18.  , 14.4 , 20.1 , 41.  , 15.  ,  4.  , 15.  , 43.  , 23.  ]])

In [13]:
arrfreq[0]

array([12.5, 14. , 21. ,  4. ,  5. , 34. ,  5. , 23. , 23. ])

In [14]:
arrfreq[:,-1]

array([23., 21., 20., 23.])

In [15]:
arrfreq[:,1:5]

array([[14.  , 21.  ,  4.  ,  5.  ],
       [12.  , 22.  ,  4.25,  7.  ],
       [45.  , 34.  ,  7.  ,  8.  ],
       [14.4 , 20.1 , 41.  , 15.  ]])

In [16]:
arrfreq[-2:,0:3]

array([[34.5, 45. , 34. ],
       [18. , 14.4, 20.1]])

Create the following 2-D array with each row representing a student and each column representing marks in Biology, Physics, Chemistry, Math and English.

85 67 78 99 78

94 69 77 89 67

93 90 89 90 56

90 78 60 78 77

In [2]:
marks = np.array([85,67,78,99,78,94,69,77,89,67,93,90,89,90,56,90,78,60,78,77])

In [3]:
marks=marks.reshape(4,5)

In [4]:
marks

array([[85, 67, 78, 99, 78],
       [94, 69, 77, 89, 67],
       [93, 90, 89, 90, 56],
       [90, 78, 60, 78, 77]])

From the array created in question 8, answer the following:

a. The maximum marks in Physics

In [15]:
np.max(np.array(marks[:,1]))

90

b. The total marks of each student

In [16]:
np.sum(marks,axis=1)

array([407, 396, 418, 383])

c. The average marks scored by students in each subject

In [17]:
np.average(marks,axis=0)

array([90.5, 76. , 76. , 89. , 69.5])

d. The minimum marks ever scored

In [11]:
np.min(marks)

56