# Exercise 5.1

In [1]:
import pandas as pd

In [2]:
obj = pd.Series([4,7,-5,3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d']=6

In [11]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [12]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [14]:
import numpy as np

In [15]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [19]:
obj3 = pd.Series(sdata)

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = pd.Series(sdata, index=states)

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4.name = 'population'

In [31]:
obj4.index.name = 'state'

In [32]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [34]:
obj.index = ['Bob','Steve','Jeff','Ryan']

In [35]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [36]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year':[2000,2001,2002,2001,2002,2003],
        'pop':[1.5,1.7,3.6,2.4,2.6,3.2]}

In [37]:
frame = pd.DataFrame(data)

In [38]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.6
5  Nevada  2003  3.2

In [39]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.6

In [40]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.6
5  2003  Nevada  3.2

In [41]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],
                     index = ['one','two','three','four','five','six'])

In [42]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.6  NaN
six    2003  Nevada  3.2  NaN

In [43]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [44]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [45]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [46]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [47]:
frame2['debt']=16.5

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.6  16.5
six    2003  Nevada  3.2  16.5

In [49]:
frame2['debt']=np.arange(6.)

In [50]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.6   4.0
six    2003  Nevada  3.2   5.0

In [51]:
val=pd.Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [52]:
frame2['debt']=val

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.6  -1.7
six    2003  Nevada  3.2   NaN

In [54]:
frame2['eastern'] = frame2.state == 'Ohio'

In [55]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.6  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [56]:
del frame2['eastern']

In [57]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [58]:
pop = {'Nevada':{2001: 2.4,2002: 2.9},
       'Ohio':{2000: 1.5,2001: 1.7,2002: 3.6}}

In [59]:
frame3 = pd.DataFrame(pop)

In [60]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [61]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [62]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [63]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [64]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [65]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [66]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [67]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [68]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.6, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [69]:
obj = pd.Series(range(3), index=['a','b','c'])

In [70]:
index = obj.index

In [71]:
index

Index(['a', 'b', 'c'], dtype='object')

In [72]:
index[1:]

Index(['b', 'c'], dtype='object')

In [73]:
index[1]='d'
#Type Error

TypeError: Index does not support mutable operations

In [75]:
labels = pd.Index(np.arange(3))

In [76]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [77]:
obj2 = pd.Series([1.5, -2.5,0],index=labels)

In [78]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [79]:
obj2.index is labels

True

In [80]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [81]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [82]:
'Ohio' in frame3.columns

True

In [83]:
2003 in frame3.index

False

In [84]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [85]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [86]:
du_label = pd.Index(['Adam','Cole','foo','foo'])

In [87]:
dup_labels.append(du_label)

Index(['foo', 'foo', 'bar', 'bar', 'Adam', 'Cole', 'foo', 'foo'], dtype='object')

In [88]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [89]:
dup_labels.difference(du_label)

Index(['bar'], dtype='object')

In [90]:
dup_labels.intersection(du_label)

Index(['foo'], dtype='object')

In [91]:
dup_labels.union(du_label)

Index(['Adam', 'Cole', 'bar', 'bar', 'foo', 'foo'], dtype='object')

In [92]:
dup_labels.isin(du_label)

array([ True,  True, False, False])

In [93]:
dup_labels.delete(3)

Index(['foo', 'foo', 'bar'], dtype='object')

In [94]:
dup_labels.drop('foo')

Index(['bar', 'bar'], dtype='object')

In [95]:
dup_labels.insert(1,'for')

Index(['foo', 'for', 'foo', 'bar', 'bar'], dtype='object')

In [96]:
numbers = pd.Index([1,2,4,5,7,8,9])

In [97]:
numbers.is_monotonic

True

In [98]:
numbers.is_unique

True

In [99]:
numbers.unique()

Int64Index([1, 2, 4, 5, 7, 8, 9], dtype='int64')

# Exercise 5.2

In [100]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [101]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [102]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [103]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [104]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [105]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [106]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [107]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
        index=['a', 'c', 'd'],columns=['Ohio', 'Texas', 'California'])

In [108]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [109]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.6  -1.7
six    2003  Nevada  3.2   NaN

In [110]:
states = ['Texas', 'Utah', 'California']

In [111]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [112]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['b'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [114]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [115]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [116]:
new_obj = obj.drop('c')

In [117]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [118]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [119]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [120]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [121]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [123]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [124]:
obj.drop('c', inplace=True)

In [125]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [126]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [127]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [128]:
obj['b']

1.0

In [129]:
obj[1]

1.0

In [130]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [131]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [132]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [133]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [134]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [135]:
obj['b':'c'] = 5

In [136]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [137]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [138]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [139]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [140]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [141]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [142]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [144]:
data[data<5]=0

In [145]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [146]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [147]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [148]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [149]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [150]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [151]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [152]:
ser = pd.Series(np.arange(3.))

In [153]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [154]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [155]:
ser2[-1]

2.0

In [156]:
ser[:1]

0    0.0
dtype: float64

In [157]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [158]:
ser.iloc[:1]

0    0.0
dtype: float64

In [159]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [160]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [161]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [162]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [163]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [164]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

In [165]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [166]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [167]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [168]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [169]:
df1 = pd.DataFrame({'A': [1, 2]})

In [170]:
df2 = pd.DataFrame({'B': [3, 4]})

In [171]:
df1

A
0  1
1  2

In [172]:
df2

B
0  3
1  4

In [173]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [174]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

In [175]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [176]:
df2.loc[1, 'b'] = np.nan

In [177]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [178]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [179]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [180]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [181]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [182]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [183]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [184]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [185]:
arr = np.arange(12.).reshape((3, 4))

In [186]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [187]:
arr[0]

array([0., 1., 2., 3.])

In [188]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [189]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [190]:
series = frame.iloc[0]

In [191]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [192]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [193]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [194]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [195]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [196]:
series3 = frame['d']

In [197]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [198]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [199]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [200]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [201]:
frame

b         d         e
Utah    1.076890  0.243993 -0.102950
Ohio   -0.243345 -1.844107 -0.113053
Texas   0.733145  0.299283 -0.089548
Oregon  1.558314 -0.055370 -1.200844

In [202]:
np.abs(frame)

b         d         e
Utah    1.076890  0.243993  0.102950
Ohio    0.243345  1.844107  0.113053
Texas   0.733145  0.299283  0.089548
Oregon  1.558314  0.055370  1.200844

In [203]:
frame

b         d         e
Utah    1.076890  0.243993 -0.102950
Ohio   -0.243345 -1.844107 -0.113053
Texas   0.733145  0.299283 -0.089548
Oregon  1.558314 -0.055370 -1.200844

In [204]:
f = lambda x: x.max() - x.min()

In [205]:
frame.apply(f)

b    1.801659
d    2.143391
e    1.111296
dtype: float64

In [206]:
frame.apply(f, axis='columns')

Utah      1.179840
Ohio      1.731054
Texas     0.822693
Oregon    2.759158
dtype: float64

In [207]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [208]:
frame.apply(f)

b         d         e
min -0.243345 -1.844107 -1.200844
max  1.558314  0.299283 -0.089548

In [209]:
format = lambda x: '%.2f' % x

In [210]:
frame.applymap(format)

b      d      e
Utah     1.08   0.24  -0.10
Ohio    -0.24  -1.84  -0.11
Texas    0.73   0.30  -0.09
Oregon   1.56  -0.06  -1.20

In [211]:
frame['e'].map(format)

Utah      -0.10
Ohio      -0.11
Texas     -0.09
Oregon    -1.20
Name: e, dtype: object

In [212]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [213]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [214]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [215]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [216]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [217]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [218]:
obj = pd.Series([4, 7, -3, 2])

In [219]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [220]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [221]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [222]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [223]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [224]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [225]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [226]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [227]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [228]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [229]:
# Assign tie values the maximum rank in the group

In [230]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [231]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})

In [232]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [233]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [234]:
obj.rank(ascending=False, method='average')

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [235]:
obj.rank(ascending=False, method='min')

0    1.0
1    7.0
2    1.0
3    3.0
4    5.0
5    6.0
6    3.0
dtype: float64

In [236]:
obj.rank(ascending=False, method='first')

0    1.0
1    7.0
2    2.0
3    3.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [237]:
obj.rank(ascending=False, method='dense')

0    1.0
1    5.0
2    1.0
3    2.0
4    3.0
5    4.0
6    2.0
dtype: float64

In [238]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [239]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [240]:
obj.index.is_unique

False

In [241]:
obj['a']

a    0
a    1
dtype: int64

In [242]:
obj['c']

4

In [243]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [244]:
df

0         1         2
a -1.273937  0.804530  1.040084
a -0.580840 -0.432248 -0.312155
b -0.762579 -1.353980  1.751060
b  2.534750  0.697553 -0.396247

In [245]:
df.loc['b']

0         1         2
b -0.762579 -1.353980  1.751060
b  2.534750  0.697553 -0.396247

# Exercise 5.3

In [246]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])

In [247]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [248]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [249]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [250]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [251]:
df.idxmax()

one    b
two    d
dtype: object

In [252]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [253]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [254]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [255]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [256]:
obj.count()

16

In [257]:
obj.min()

'a'

In [258]:
obj.max()

'c'

In [259]:
obj = pd.Index([4,7,5,6,1,2,9,8,3])

In [260]:
obj.argmin()

4

In [261]:
obj.argmax()

6

In [262]:
obj.min()

1

In [263]:
obj.max()

9

In [264]:
import numpy as np

In [265]:
dfa=pd.DataFrame(np.random.randint(1,20,12).reshape(3,4),index=['A','B','C'],columns=['Q1','Q2','Q3','Q4'])
dfb=pd.DataFrame(np.random.randint(1,20,12).reshape(3,4),index=['D','E','F'],columns=['Q1','Q2','Q3','Q4'])

In [266]:
df = pd.concat([dfa,dfb])

In [267]:
df

Q1  Q2  Q3  Q4
A   9   1   3  18
B  11   6  15   7
C   7   3   7   8
D   6   8  19   4
E   4  18  16  19
F   6   9   9   9

In [268]:
df.count()

Q1    6
Q2    6
Q3    6
Q4    6
dtype: int64

In [269]:
df.describe()

Q1         Q2         Q3         Q4
count   6.000000   6.000000   6.000000   6.000000
mean    7.166667   7.500000  11.500000  10.833333
std     2.483277   5.958188   6.123724   6.177918
min     4.000000   1.000000   3.000000   4.000000
25%     6.000000   3.750000   7.500000   7.250000
50%     6.500000   7.000000  12.000000   8.500000
75%     8.500000   8.750000  15.750000  15.750000
max    11.000000  18.000000  19.000000  19.000000

In [270]:
df.min()

Q1    4
Q2    1
Q3    3
Q4    4
dtype: int32

In [271]:
df.max()

Q1    11
Q2    18
Q3    19
Q4    19
dtype: int32

In [272]:
df.cumprod()

Q1     Q2      Q3      Q4
A      9      1       3      18
B     99      6      45     126
C    693     18     315    1008
D   4158    144    5985    4032
E  16632   2592   95760   76608
F  99792  23328  861840  689472

In [273]:
df.cumsum()

Q1  Q2  Q3  Q4
A   9   1   3  18
B  20   7  18  25
C  27  10  25  33
D  33  18  44  37
E  37  36  60  56
F  43  45  69  65

In [274]:
df.cummin()

Q1  Q2  Q3  Q4
A   9   1   3  18
B   9   1   3   7
C   7   1   3   7
D   6   1   3   4
E   4   1   3   4
F   4   1   3   4

In [275]:
df.cummax()

Q1  Q2  Q3  Q4
A   9   1   3  18
B  11   6  15  18
C  11   6  15  18
D  11   8  19  18
E  11  18  19  19
F  11  18  19  19

In [276]:
df.skew()

Q1    0.539827
Q2    1.123321
Q3   -0.215555
Q4    0.646902
dtype: float64

In [277]:
df.kurt()
#don't know what it does

Q1   -0.148137
Q2    1.726403
Q3   -1.574187
Q4   -1.656925
dtype: float64

In [278]:
df.idxmin()

Q1    E
Q2    A
Q3    A
Q4    D
dtype: object

In [279]:
df.idxmax()

Q1    B
Q2    E
Q3    D
Q4    E
dtype: object

In [280]:
df.quantile()

Q1     6.5
Q2     7.0
Q3    12.0
Q4     8.5
Name: 0.5, dtype: float64

In [281]:
df.sum()

Q1    43
Q2    45
Q3    69
Q4    65
dtype: int64

In [282]:
df.mean()

Q1     7.166667
Q2     7.500000
Q3    11.500000
Q4    10.833333
dtype: float64

In [283]:
df.median()

Q1     6.5
Q2     7.0
Q3    12.0
Q4     8.5
dtype: float64

In [284]:
df.mad

<bound method NDFrame._add_numeric_operations.<locals>.mad of    Q1  Q2  Q3  Q4
A   9   1   3  18
B  11   6  15   7
C   7   3   7   8
D   6   8  19   4
E   4  18  16  19
F   6   9   9   9>

In [285]:
df.prod()

Q1     99792
Q2     23328
Q3    861840
Q4    689472
dtype: int32

In [286]:
df.var()

Q1     6.166667
Q2    35.500000
Q3    37.500000
Q4    38.166667
dtype: float64

In [287]:
df.std()

Q1    2.483277
Q2    5.958188
Q3    6.123724
Q4    6.177918
dtype: float64

In [288]:
df.cumsum()

Q1  Q2  Q3  Q4
A   9   1   3  18
B  20   7  18  25
C  27  10  25  33
D  33  18  44  37
E  37  36  60  56
F  43  45  69  65